-- Copyright 2026 Scott Friedman. Licensed under the Apache License, Version 2.0.

-- Compliance training modules that map to attest:* IAM tags.
-- Module IDs must match the keys in internal/training/service.go moduleTagMap.

INSERT INTO training_modules (name, title, description, category, difficulty, estimated_minutes, content) VALUES

('cui-fundamentals', 'Controlled Unclassified Information (CUI)',
 'Required for CMMC Level 2. Covers CUI categories, handling, marking, and safeguarding under 32 CFR Part 2002.',
 'compliance', 'intermediate', 45,
 '{"sections": [{"id": "intro", "title": "What is CUI?", "type": "text", "content": "Controlled Unclassified Information (CUI) is information the Government creates or possesses that requires safeguarding or dissemination controls consistent with applicable laws, regulations, and Government-wide policies. CUI is not classified information, but it must be protected. Common research CUI categories include: export controlled technical data, proprietary business information, and pre-decisional government information."}, {"id": "handling", "title": "Handling Requirements", "type": "text", "content": "CUI must be stored in systems that meet NIST SP 800-171 requirements. This means: encryption at rest and in transit, access limited to authorized users, audit logging of all access, and timely reporting of any incidents. In AWS environments managed by attest, these controls are enforced automatically via Cedar policies once your training is current."}, {"id": "marking", "title": "Marking and Dissemination", "type": "text", "content": "CUI documents must be marked with the CUI designation and any applicable category markings. Before sharing CUI with collaborators, verify they have the appropriate agreements and system authorizations. Foreign nationals require additional review — consult your Export Control office."}]}'),

('hipaa-privacy-security', 'HIPAA Security & Privacy',
 'Required for PHI access. Covers the HIPAA Security Rule, minimum necessary standard, breach notification, and workforce training.',
 'compliance', 'intermediate', 60,
 '{"sections": [{"id": "intro", "title": "HIPAA Overview", "type": "text", "content": "The Health Insurance Portability and Accountability Act (HIPAA) establishes national standards for protecting individually identifiable health information, known as Protected Health Information (PHI). As a researcher using AWS environments with PHI, you are a member of the covered entity workforce and must comply with both the Privacy Rule and Security Rule."}, {"id": "minimum-necessary", "title": "Minimum Necessary Standard", "type": "text", "content": "The HIPAA Privacy Rule requires that you request, use, and disclose only the minimum PHI necessary to accomplish the intended purpose. This means: do not request access to data beyond your study protocol, de-identify data whenever it serves the research purpose, and use limited datasets (with direct identifiers removed) when full PHI is not required."}, {"id": "security", "title": "Security Safeguards", "type": "text", "content": "The HIPAA Security Rule requires administrative, physical, and technical safeguards for electronic PHI (ePHI). In your AWS research environment: data is encrypted at rest and in transit, access is logged and audited, and your IAM role is evaluated by Cedar policies that verify your HIPAA training is current before allowing access to PHI-tagged resources."}]}'),

('security-awareness', 'Security Awareness',
 'Annual security awareness training. Satisfies CMMC AC.1.001, NIST 800-171 3.2.2, and institutional policy workforce training requirements.',
 'compliance', 'beginner', 30,
 '{"sections": [{"id": "intro", "title": "Why Security Awareness Matters", "type": "text", "content": "Security incidents at research institutions frequently originate from phishing attacks, credential misuse, and misconfigured cloud resources — not sophisticated technical exploits. This training covers the practical habits that prevent the most common incidents."}, {"id": "phishing", "title": "Phishing and Social Engineering", "type": "text", "content": "Verify unexpected requests for credentials or data access through a separate channel. AWS will never email you asking for your access keys. If you receive a suspicious request claiming to be from IT or AWS, call the requestor directly rather than replying to the message."}, {"id": "credentials", "title": "Credential Hygiene", "type": "text", "content": "Never share AWS credentials. Never commit access keys to source control. Use IAM roles rather than long-term access keys wherever possible. Enable MFA on your IAM user. Rotate any accidentally exposed credentials immediately and report the incident to your institution."}]}'),

('ferpa-basics', 'FERPA',
 'Required for student record access. Covers education records, disclosure limitations, legitimate educational interest, and de-identification.',
 'compliance', 'beginner', 30,
 '{"sections": [{"id": "intro", "title": "What FERPA Covers", "type": "text", "content": "The Family Educational Rights and Privacy Act (FERPA) protects the privacy of student education records. Education records include any record directly related to a student and maintained by the institution. Research involving student records requires either student consent, a FERPA exception, or use of de-identified data."}, {"id": "access", "title": "Legitimate Educational Interest", "type": "text", "content": "Faculty and staff may access student records only when they have a legitimate educational interest — a direct need to know the information in order to fulfill a professional responsibility. Curiosity, even professional curiosity, does not constitute legitimate educational interest. Document your basis for access before requesting it."}, {"id": "deidentification", "title": "De-identification", "type": "text", "content": "FERPA-protected data can be used in research without consent if it is de-identified. De-identification requires removing all direct identifiers (name, ID, SSN, email, etc.) and any combination of characteristics that could reasonably be used to identify the student. Consult your IRB and privacy office before determining that a dataset is sufficiently de-identified."}]}'),

('itar-export-control', 'ITAR / Export Controls',
 'Required for DoD-funded research with controlled technical data or foreign national collaborators. Covers deemed exports, TCPs, and EAR/ITAR distinctions.',
 'compliance', 'advanced', 60,
 '{"sections": [{"id": "intro", "title": "Export Control Basics", "type": "text", "content": "Export control laws (ITAR and EAR) regulate the transfer of controlled technology, information, and items to foreign persons — including within the United States (deemed exports). Research involving DoD contracts, controlled technical data, or foreign national collaborators requires careful compliance."}, {"id": "deemed-exports", "title": "Deemed Exports", "type": "text", "content": "A deemed export occurs when controlled technology or technical data is released to a foreign national in the U.S. In a research context, this includes sharing technical data with a foreign national postdoc or collaborator, even in an AWS environment. Before providing foreign national team members with access to controlled research data, consult your Export Control office for an export license determination."}, {"id": "tcp", "title": "Technology Control Plans", "type": "text", "content": "A Technology Control Plan (TCP) documents how your lab will protect controlled technology. For DoD-funded projects with foreign national personnel, a TCP is typically required. The TCP specifies: what technology is controlled, who has access and why, physical and technical controls in place, and procedures for handling violations. Your attest.provabl.dev compliance navigator will flag TCP requirements when it detects DoD funding + foreign national collaborators in your project record."}]}'),

('data-classification', 'Data Classification',
 'Institutional data classification framework. Covers identifying sensitivity levels, handling requirements per classification, and storage and transmission controls.',
 'compliance', 'beginner', 30,
 '{"sections": [{"id": "intro", "title": "Why Data Classification Matters", "type": "text", "content": "Not all research data requires the same level of protection. Classifying your data correctly ensures you apply the right controls — neither over-protecting public data (which creates unnecessary friction) nor under-protecting sensitive data (which creates compliance risk). Your AWS environment uses the attest:data-classification tag on accounts to enforce appropriate controls automatically."}, {"id": "levels", "title": "Classification Levels", "type": "text", "content": "Most institutional frameworks include four levels: Public (can be freely shared), Internal (institutional use, not for public release), Confidential (limited access, business-sensitive or personally identifiable), and Restricted/Controlled (highest sensitivity: PHI, CUI, student records, financial data, export-controlled data). When in doubt, classify higher and consult your data steward."}, {"id": "handling", "title": "Handling by Classification", "type": "text", "content": "Restricted/Controlled data must be stored in an authorized enclave (your AWS SRE), encrypted at rest and in transit, and accessed only by personnel with appropriate training and authorizations. Do not store Restricted data on personal devices, in personal cloud storage, or in systems not authorized for that classification level."}]}'),

('nih-research-security', 'NIH Research Security (NOT-OD-26-017)',
 'Required by NIH NOT-OD-26-017 for all key personnel on NIH-funded projects. Covers foreign influence disclosure, research integrity, and institutional reporting.',
 'compliance', 'intermediate', 45,
 '{"sections": [{"id": "intro", "title": "NIH Research Security Requirements", "type": "text", "content": "NIH Notice NOT-OD-26-017 requires all key personnel on NIH-funded awards to complete research security training within 12 months of award issuance and every 12 months thereafter. This training covers the obligations to disclose foreign affiliations, understand research integrity principles, and report suspected violations."}, {"id": "disclosure", "title": "Foreign Affiliation Disclosure", "type": "text", "content": "Key personnel must disclose all foreign affiliations, positions, and financial interests — including foreign talent recruitment programs, honorary positions, and foreign funding sources — both at application and throughout the award period. Failure to disclose is research misconduct. If your affiliations change, notify your institution immediately. Disclosures are reviewed by NIH and may require prior approval."}, {"id": "reporting", "title": "Reporting Obligations", "type": "text", "content": "You are required to report to your institution any approaches from foreign entities seeking inappropriate access to your research. This includes requests for unpublished data, attempts to recruit you to foreign talent programs, and offers of foreign funding or affiliations. Your institution will assess whether the incident requires reporting to NIH. When in doubt, report — non-reporting carries greater risk than false-positive reporting."}]}')

ON CONFLICT (name) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  content = EXCLUDED.content;
